name: Release Beta build through Fastlane on push to testing

on:
  workflow_dispatch:
    inputs:
      host:
        description: "env backend host"
        required: true
        default: "warning"

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "BACKEND_HOST: ${{ github.event.inputs.host }}"
